site_name: Social Integrator
site_description: A Python library for programmatic social networking integration
site_author: DevOpsX Team
repo_url: https://github.com/yourusername/social-integrator
repo_name: social-integrator

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Authentication: user-guide/authentication.md
    - Platforms:
      - Twitter: user-guide/platforms/twitter.md
    - Rate Limiting: user-guide/rate-limiting.md
    - Error Handling: user-guide/error-handling.md
  - API Reference:
    - Core: api/core.md
    - Platforms: api/platforms.md
    - Authentication: api/auth.md
    - Utils: api/utils.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Release Process: development/releasing.md
  - About:
    - License: about/license.md
    - Changelog: about/changelog.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_if_no_docstring: true
            heading_level: 2
            members_order: source
            docstring_style: google
            merge_init_into_class: true
            show_signature_annotations: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/social-integrator
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/social-integrator/
  version:
    provider: mike

copyright: Copyright &copy; 2023 DevOpsX Team
